language: objective-c
osx_image: xcode7.2

before_install:
  - bundle install

script:
  - bundle exec rake test

env:
  - "NAME=iPhone VERSION=8.0"
  - "NAME=iPhone VERSION=9.0"
  - "NAME=iPad VERSION=8.0"
  - "NAME=iPad VERSION=9.0"