language: objective-c
osx_image: xcode7.2

install:
  - bundle install
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - bundle exec rake test

env:
  - "NAME=iPhone VERSION=8.0"
  - "NAME=iPhone VERSION=9.0"
  - "NAME=iPad VERSION=8.0"
  - "NAME=iPad VERSION=9.0"