language: objective-c
osx_image: xcode8

before_install:
 - rvm get head

install:
  - bundle install
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - bundle exec rake test

env:
  - "NAME='iPhone 6' VERSION=10.0"
  - "NAME='iPhone 6' VERSION=9.0"
  - "NAME='iPad Air' VERSION=10.0"
  - "NAME='iPad Air' VERSION=9.0"
